### PR TITLE
Fix escape_html(), const namespaces

### PR DESCRIPTION
**Pull request by suurjaak**
Hello again! 

I noticed some minor issues with step, hope you don't mind a pull request to fix them.

Main things:
- made escape_html() work in Py3 (it still referenced basestring)
- made expand() and stream() not modify the given namespace object

### CODE REVIEW

**Comment by dotpy** [comment]
Hi!
Thanks a lot for this fix!

**Comment by suurjaak** [comment]
Thank *you*, for providing such an awesome useful little library :) I've been using it in a number of projects, to generate various kinds of content. 

Can you also tag the release and upload it to PyPI?

I have also made some other changes to my local fork:
- caching and reusing compiled code objects
- constructor accepting auto-escape option (`{{x}}`  on template providing escaped content and `{{!x}}` unescaped)
- constructor accepting postprocessing callbacks
- `get(name)` added to template functions, returning named variable or given default or None
- skipping conversion to bytes in `Template.stream()` if empty encoding given
- skipping empty `echo("""""")` statements between consecutive code blocks
- `Template.stream()` accepting `buffer_size` parameter
- retaining first trailing whitespace when stripping chunks in `Template.stream()` (to avoid completely stripping all whitespace from unbuffered streams)

All in all, these do not make the library much bigger; result is 4 lines longer than the current master. If you are interested, I can open another pull request. You can see the changes at https://github.com/dotpy/step/compare/master...suurjaak:step:master.

**Comment by suurjaak** [comment]
@dotpy Ping?

**Comment by dotpy** [comment]
Hi,
apologies for the delay, I missed your previous comment!
Thanks a lot for your feedback and your improvements: I've merged them right now!
I'll upload the new release to PyPI as soon as possible and get back to you.
Thanks again and best regards!

**Comment by suurjaak** [comment]
@dotpy Can you also put the latest on PyPI? 

Btw, I think the changes are large enough to merit bumping the minor version at least, if not the major.

**Comment by dotpy** [comment]
Hi @suurjaak ,
Apologies for the delay, I have just uploaded the new version to PyPi: https://pypi.org/project/step-template/0.0.4/
Best regards!

**Pull request merged**
