### PR TITLE
improve code and fix issue#5

### PR DESCRIPTION
**Pull request by taojy123**
I update the setup.py and testcases.
Could you upload the newest version to pypi, please.
So I can use it by pip install, Thankyou 😀

### CODE REVIEW

**Comment by dotpy** [comment]
Hi @taojy123 ,
Thanks a lot for your patch.
I'm on vacation right now, I'll upload it to pypi as soon as I'll be back.
Cheers,
Daniele

**Comment by taojy123** [comment]
Hi，are you forgot upload the newest version to pypi？😬

**Comment by dotpy** [comment]
Hi,
Well, to be honest... yes! :-D
Sorry for the long wait, I've uploaded it a few minutes ago.
Cheers,
Daniele

**Comment by taojy123** [comment]
Thankyou very much 👍

**Pull request merged**
